name: PRs to upstream from fork

# Defines when the workflow should run
on:
  pull_request_target:
    branches:
      - main

# Jobs to be executed
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }} # use current PRs code

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7 # Specify your Terraform version here

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate
